version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:21.6.2

    steps:
      - checkout
      - run:
          name: Install Dependancies
          command: npm install
      - run:
          name: Install Parcel
          command: npm install -g parcel-bundler
      - run:
          name: Build with Parcel
          command: parcel build index.html --no-minify

workflows:
  deploy:
    jobs:
      - test